In [1]:
import pandas as pd
import numpy as np

In [ ]:
alpha = 2.0
results_path = f"../outputs/run_infojigsaw/alpha={alpha}/max_depth=inf_tolerance=0.001/seed=1234/results.csv"
results = pd.read_csv(results_path)
results = results[results["turn"] > 1]
results.groupby(["model","sample_id"]).apply(lambda x: x.loc[x["turn"].idxmax(),"nll"]).reset_index().groupby("model").agg(["mean", "std"])

/tmp/ipykernel_246393/2241681164.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  results.groupby(["model","sample_id"]).apply(lambda x: x.loc[x["turn"].idxmax(),"nll"]).reset_index().groupby("model").agg(["mean", "std"])

           sample_id                     0
                mean         std      mean       std
model
crsa       624.16129  337.417049  0.813274  1.022926
literal    624.16129  337.417049  0.816443  1.007654
multi_rsa  624.16129  337.417049  0.813071  1.022987

In [8]:
alpha = 2.0
results_path = f"../outputs/run_infojigsaw/results.csv"
results = pd.read_csv(results_path)
results.groupby("model").agg(["mean", "std"]).reset_index()

       model sample_idx             cat_accuracy             cat_nll  \
                   mean         std         mean       std      mean
0       crsa      604.5  349.441221     0.747107  0.434850  0.899230
1    literal      604.5  349.441221     0.755372  0.430044  0.893829
2  multi_rsa      604.5  349.441221     0.747107  0.434850  0.899147

            utt_accuracy             utt_nll
        std         mean       std      mean           std
0  1.091437     0.016529  0.127551  4.276665  2.346788e-05
1  1.065573     0.085124  0.279181       inf           NaN
2  1.091467     0.016529  0.127551  4.276666  6.388704e-13